In [5]:
print("Hello ji" , end=" ")
print("Bolo ji")

Hello ji Bolo ji


In [6]:
list = [ 3 ,4 ,5]
list.pop()

5

In [13]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5,6,7,8,9])
print(array)

[1 2 3 4 5 6 7 8 9]


In [5]:
all_5 = np.full((3,3),5)
print(all_5)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [6]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
evenly = np.linspace(1,100,10,dtype=int)
evenly

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

In [15]:
random = np.random.randint(10,21,(2, 2))
random

array([[16, 15],
       [17, 10]], dtype=int32)